export enum OrderStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum OrderType {
  MEDICAL_PRESCRIPTION_ORDER = 'MEDICAL_PRESCRIPTION_ORDER',
  MEDICAL_CONSULTATION_ORDER = 'MEDICAL_CONSULTATION_ORDER',
  PRODUCT_SALE_ORDER = 'PRODUCT_SALE_ORDER',
}
