name: Docker Build Dev

on:
  push:
    branches: [develop]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/docker-build-dev.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: dev
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-juan-pablo-ii:dev
            ${{ secrets.DOCKERHUB_USERNAME }}/api-juan-pablo-ii:${{ github.sha }}-dev
      # Añade este job al workflow de desarrollo
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old images
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'api-juan-pablo-ii'
          package-type: 'container'
          min-versions-to-keep: 5
