name: Docker Build and Deploy

on:
  push:
    branches: [ main, stage ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/docker-build-deploy.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set environment variables
        run: |
          # Get repository name in lowercase, removing any organization prefix
          REPO_NAME="$(echo "${{ github.repository }}" | sed 's/.*\///' | tr '[:upper:]' '[:lower:]')"
          echo "REPO_NAME=${REPO_NAME}" >> "${GITHUB_ENV}"
          
          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
            echo "ENV_TAG=prod" >> "${GITHUB_ENV}"
          else
            echo "ENV_TAG=stage" >> "${GITHUB_ENV}"
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest-${{ env.ENV_TAG }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest-${{ env.ENV_TAG }}
          cache-to: type=inline
          provenance: false
          sbom: false

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          REPO_NAME="$(echo "${{ github.repository }}" | sed 's/.*\///' | tr '[:upper:]' '[:lower:]')"
          echo "REPO_NAME=${REPO_NAME}" >> "${GITHUB_ENV}"
          
          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
            echo "ENV_TAG=prod" >> "${GITHUB_ENV}"
          else
            echo "ENV_TAG=stage" >> "${GITHUB_ENV}"
          fi
          echo "DOCKER_TAG=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}" >> "${GITHUB_ENV}"

      - name: Configure SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ github.ref == 'refs/heads/main' && secrets.PROD_SSH_PRIVATE_KEY || secrets.STAGE_SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace
          config: |
            Host deployment-target
              HostName ${{ github.ref == 'refs/heads/main' && secrets.PROD_SERVER_HOST || secrets.STAGE_SERVER_HOST }}
              User ${{ github.ref == 'refs/heads/main' && secrets.PROD_SSH_USERNAME || secrets.STAGE_SSH_USERNAME }}
              Port ${{ github.ref == 'refs/heads/main' && secrets.PROD_SSH_PORT || secrets.STAGE_SSH_PORT || 22 }}
              StrictHostKeyChecking no

      - name: Update docker-compose on server
        env:
          DOCKER_TAG: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ github.sha }}
          ENV_TAG: ${{ env.ENV_TAG }}
        run: |
          ssh deployment-target "bash -s" << 'ENDSSH'
            # Export variables passed from GitHub Actions
            export DOCKER_TAG="$DOCKER_TAG"
            export ENV_TAG="$ENV_TAG"
            
            # Pull new image
            docker pull "$DOCKER_TAG"
            
            # Update the API service without affecting others
            cd ~/docker/acide/juan-pablo-ii
            
            # Verificar si el archivo docker-compose existe
            if [ ! -f "docker-compose.$ENV_TAG.yml" ]; then
              echo "Error: docker-compose.$ENV_TAG.yml not found"
              exit 1
            fi
            
            # Update image in docker-compose file
            sed -i "s|image: .*|image: $DOCKER_TAG|" "docker-compose.$ENV_TAG.yml"
            
            # Restart only the API service
            if command -v docker-compose &> /dev/null; then
              docker-compose -f "docker-compose.$ENV_TAG.yml" up -d --no-deps api
            else
              docker compose -f "docker-compose.$ENV_TAG.yml" up -d --no-deps api
            fi
            
            # Cleanup old images (usando un comando compatible con versiones antiguas)
            docker images -q --filter "dangling=true" | xargs -r docker rmi
ENDSSH
